import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { tempRepo, type TempRepo } from "../../test/repo.js";
import { readAttributes } from "./attributes.js";
import { classifyFiles } from "./read.js";

const PATHS = ["pnpm-lock.yaml", "docs/a.md", "src/x.ts", "src/x.spec.ts"];

describe("readAttributes", () => {
  let repo: TempRepo;
  let base: string;

  beforeAll(() => {
    repo = tempRepo();
    repo.write(
      ".gitattributes",
      "pnpm-lock.yaml strauss-class=lockfile\ndocs/** linguist-documentation\n",
    );
    repo.write("sub/.gitattributes", "*.ts strauss-class=test\n");
    repo.write("src/x.ts", "export {};\n");
    base = repo.commit("base");
    // The branch marks its own source generated; the base does not agree.
    repo.write(
      ".gitattributes",
      "pnpm-lock.yaml strauss-class=lockfile\ndocs/** linguist-documentation\nsrc/** linguist-generated\n",
    );
    repo.commit("head");
  });

  afterAll(() => repo.cleanup());

  test("classes come from the base, not from the branch", async () => {
    const attributes = await readAttributes(repo.root, base, PATHS);
    expect(attributes.pinned).toBe(true);
    expect(attributes.repoDeclares).toBe(true);
    expect(Object.fromEntries(attributes.classes)).toEqual({
      "pnpm-lock.yaml": {
        class: "lockfile",
        reason: "attribute strauss-class=lockfile",
      },
      "docs/a.md": {
        class: "docs",
        reason: "attribute linguist-documentation",
      },
    });
  });

  test("without a base the working tree answers, and says so", async () => {
    const attributes = await readAttributes(repo.root, null, PATHS);
    expect(attributes.pinned).toBe(false);
    expect(attributes.classes.get("src/x.ts")).toEqual({
      class: "generated",
      reason: "attribute linguist-generated",
    });
  });

  test("an unsafe base reads no attribute and declares nothing", async () => {
    const attributes = await readAttributes(repo.root, "--all", PATHS);
    expect(attributes).toEqual({
      classes: new Map(),
      repoDeclares: false,
      pinned: false,
    });
  });
});

describe("repoDeclares", () => {
  test.for([
    ["no .gitattributes", {}, false],
    ["only line endings", { ".gitattributes": "* text=auto eol=lf\n" }, false],
    ["a root class", { ".gitattributes": "*.lock linguist-generated\n" }, true],
    ["a nested class", { "a/b/.gitattributes": "x strauss-class=ci\n" }, true],
  ] as const)("%s → %s", async ([, files, expected]) => {
    const repo = tempRepo();
    try {
      repo.write("src/a.ts", "export {};\n");
      for (const [path, text] of Object.entries(files)) repo.write(path, text);
      const base = repo.commit("base");
      expect((await readAttributes(repo.root, base, [])).repoDeclares).toBe(
        expected,
      );
    } finally {
      repo.cleanup();
    }
  });

  test("outside a repository nothing is declared", async () => {
    const dir = mkdtempSync(join(tmpdir(), "code-diff-not-a-repo-"));
    try {
      expect((await readAttributes(dir, null, ["a.md"])).repoDeclares).toBe(
        false,
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("classifyFiles", () => {
  let repo: TempRepo;
  let base: string;

  beforeAll(() => {
    repo = tempRepo();
    repo.write(".gitattributes", "docs/** linguist-documentation\n");
    base = repo.commit("base");
    repo.write("docs/a.md", "# A\n");
    repo.write("src/gen.ts", "// Code generated by hand-rolled script\n");
    repo.write("README.md", "# Readme\n");
    repo.commit("head");
  });

  afterAll(() => repo.cleanup());

  const files = [
    { filePath: "docs/a.md", hunks: [] },
    { filePath: "src/gen.ts", hunks: [] },
    { filePath: "README.md", hunks: [] },
  ];

  test("attribute, banner, then source — the table is off here", async () => {
    const result = await classifyFiles(repo.root, files, { base });
    expect(result).toEqual({
      files: [
        {
          filePath: "docs/a.md",
          class: "docs",
          reason: "attribute linguist-documentation",
        },
        {
          filePath: "src/gen.ts",
          class: "generated",
          reason: "generated-header code generated by",
        },
        { filePath: "README.md", class: "source", reason: "default" },
      ],
    });
  });

  test("a subdirectory as the root reads the same repository", async () => {
    repo.write("src/keep.ts", "export {};\n");
    expect(
      await classifyFiles(join(repo.root, "src"), files, { base }),
    ).toEqual(await classifyFiles(repo.root, files, { base }));
  });

  test("no base is answered, with a note", async () => {
    const result = await classifyFiles(repo.root, files, { base: null });
    expect(result.notes).toEqual([
      ".gitattributes read from the working tree: no base was given",
    ]);
  });
});
