import { describe, expect, test } from "vitest";
import { classifyDiff } from "./classify.js";
import type {
  ClassifyFile,
  ClassifyOptions,
  Declared,
  DiffClass,
  Verdict,
} from "./model.js";
import { DEFAULT_PATH_RULES } from "./rules.js";

function file(
  filePath: string,
  rest: Partial<ClassifyFile> = {},
): ClassifyFile {
  return { filePath, hunks: [], ...rest };
}

function classOf(input: ClassifyFile, options: ClassifyOptions = {}) {
  return (classifyDiff([input], options)[0] as { class: DiffClass }).class;
}

/** One path per row of the default table, and the rows that went. */
const PATHS: Record<string, DiffClass> = {
  "src/order.spec.ts": "test",
  "src/__tests__/order.ts": "test",
  "test/helpers.ts": "test",
  ".github/workflows/ci.yml": "ci",
  ".circleci/config.yml": "ci",
  ".gitlab-ci.yml": "ci",
  "docs/README.md": "docs",
  "CHANGELOG.md": "docs",
  "pnpm-lock.yaml": "lockfile",
  "go.sum": "lockfile",
  // No longer guessed: the repository has to say so.
  "package.json": "source",
  "tsconfig.build.json": "source",
  "vitest.config.ts": "source",
  ".strauss/kb/log.jsonl": "source",
  Dockerfile: "source",
  "infra/main.tf": "source",
  LICENSE: "source",
  "src/order.service.ts": "source",
  "contest/foo.ts": "source",
};

describe("classifyDiff default path table", () => {
  test("every row of the table is reachable", () => {
    const reached = new Set(
      Object.keys(PATHS).flatMap((path) => {
        const rule = DEFAULT_PATH_RULES.find((entry) => entry.test.test(path));
        return rule ? [rule.name] : [];
      }),
    );
    expect([...reached].sort()).toEqual(
      DEFAULT_PATH_RULES.map((rule) => rule.name).sort(),
    );
  });

  test.for(Object.entries(PATHS))("%s is %s", ([path, expected]) => {
    expect(classOf(file(path))).toBe(expected);
  });

  test("a repository that declares classes turns the table off", () => {
    expect(
      classifyDiff([file("docs/README.md")], { repoDeclares: true })[0],
    ).toMatchObject({ class: "source", reason: "default" });
  });
});

describe("classifyDiff precedence", () => {
  const banner = file("docs/types.md", {
    header: ["<!-- Code generated by protoc. DO NOT EDIT. -->"],
  });
  const attributes = new Map<string, Verdict>([
    [
      "docs/types.md",
      { class: "docs", reason: "attribute linguist-documentation" },
    ],
  ]);
  const declared = (verdict: Verdict): Declared => ({
    file: () => verdict,
    hunk: () => undefined,
  });

  test("a banner beats the path table, named by the first marker in the list", () => {
    expect(classifyDiff([banner])[0]).toMatchObject({
      class: "generated",
      reason: "generated-header do not edit",
    });
  });

  test("an attribute beats the banner", () => {
    expect(classifyDiff([banner], { attributes })[0]).toMatchObject({
      class: "docs",
      reason: "attribute linguist-documentation",
    });
  });

  test("a declaration beats the attribute", () => {
    expect(
      classifyDiff([banner], {
        attributes,
        declared: declared({ class: "boilerplate", reason: "kb-override x" }),
      })[0],
    ).toMatchObject({ class: "boilerplate", reason: "kb-override x" });
  });

  test("a banner past the window is not a banner", () => {
    expect(
      classOf(
        file("src/late.ts", {
          header: [...Array(20).fill("x"), "// @generated"],
        }),
      ),
    ).toBe("source");
  });

  test("with no header, the diff's added lines inside the window stand in", () => {
    expect(
      classOf(
        file("src/gen.ts", {
          hunks: [{ startLine: 1, endLine: 1, lines: ["// @generated"] }],
        }),
      ),
    ).toBe("generated");
  });
});

describe("classifyDiff per hunk", () => {
  const hunks = [
    { startLine: 5, endLine: 5 },
    { startLine: 9, endLine: 9 },
  ];

  test("a hunk declaration classifies that hunk only", () => {
    const [result] = classifyDiff([file("src/a.ts", { hunks })], {
      declared: {
        file: () => undefined,
        hunk: (_path, hunk) =>
          hunk.startLine === 5
            ? { class: "boilerplate", reason: "kb-override fact.barrel" }
            : undefined,
      },
    });
    expect(result).toMatchObject({ class: "source", reason: "default" });
    expect(result?.hunks).toEqual([
      {
        startLine: 5,
        endLine: 5,
        class: "boilerplate",
        reason: "kb-override fact.barrel",
      },
      { startLine: 9, endLine: 9, class: "source", reason: "default" },
    ]);
  });

  test("hunks are absent when every one agrees with the file", () => {
    expect(classifyDiff([file("src/a.ts", { hunks })])[0]).not.toHaveProperty(
      "hunks",
    );
  });
});

describe("classifyDiff drops the guesses", () => {
  test("a rename is carried but not a class of its own", () => {
    expect(
      classifyDiff([
        file("src/new.ts", { renamedFrom: "src/old.ts", similarity: 100 }),
      ])[0],
    ).toEqual({
      filePath: "src/new.ts",
      class: "source",
      reason: "default",
      renamedFrom: "src/old.ts",
    });
  });

  test("a file of import lines is source", () => {
    expect(
      classOf(
        file("src/index.ts", {
          hunks: [
            {
              startLine: 30,
              endLine: 31,
              lines: ['import { a } from "./a.js";', 'export * from "./b.js";'],
            },
          ],
        }),
      ),
    ).toBe("source");
  });
});
