import type { AttributeValues } from "@saasontools/git-guard";
import type { DiffClass, Verdict } from "./model.js";

export type PathRule = { name: string; class: DiffClass; test: RegExp };

/**
 * For a repository that declares no class attribute; first match wins. Every
 * other class must be written in the repository.
 */
export const DEFAULT_PATH_RULES: readonly PathRule[] = [
  {
    name: "test-path",
    class: "test",
    test: /(^|\/)(__tests__|__mocks__|tests?)\/|\.(spec|test)\.[^/]+$/,
  },
  {
    name: "ci-path",
    class: "ci",
    test: /(^|\/)(\.github|\.circleci|\.buildkite)\/|(^|\/)\.gitlab-ci\.yml$/,
  },
  { name: "docs-path", class: "docs", test: /\.md$|(^|\/)docs\// },
  {
    name: "lockfile-path",
    class: "lockfile",
    test: /(^|\/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock|Cargo\.lock|go\.sum)$/,
  },
];

export function pathRule(filePath: string): Verdict | undefined {
  const rule = DEFAULT_PATH_RULES.find((entry) => entry.test.test(filePath));
  return rule && { class: rule.class, reason: rule.name };
}

/** How far into a file a generator's banner counts as one. */
export const HEADER_LINES = 20;

/** Banners a generator writes, matched case-insensitively. */
export const GENERATED_MARKERS: readonly RegExp[] = [
  /@generated\b/i,
  /\bdo not edit\b/i,
  /\bcode generated by\b/i,
  /\bthis file was automatically generated\b/i,
];

export function generatedMarker(lines: readonly string[]): string | undefined {
  for (const line of lines.slice(0, HEADER_LINES)) {
    const hit = GENERATED_MARKERS.find((marker) => marker.test(line));
    if (hit) return hit.source.replaceAll("\\b", "");
  }
  return undefined;
}

/** The attributes the classifier reads, in the order they win. */
export const CLASS_ATTRIBUTES = [
  "linguist-generated",
  "linguist-vendored",
  "linguist-documentation",
  "strauss-class",
] as const;

/** `strauss-class` values honoured; `source` raises scrutiny, never lowers it. */
const STRAUSS_CLASSES = new Set<DiffClass>([
  "test",
  "ci",
  "config",
  "lockfile",
  "source",
]);

/** One path's attribute values as a verdict, or nothing when none applies. */
export function attributeVerdict(values: AttributeValues): Verdict | undefined {
  const set = (name: string) =>
    values[name] === "set" || values[name] === "true";
  if (set("linguist-generated")) {
    return { class: "generated", reason: "attribute linguist-generated" };
  }
  if (set("linguist-vendored")) {
    return { class: "generated", reason: "attribute linguist-vendored" };
  }
  if (set("linguist-documentation")) {
    return { class: "docs", reason: "attribute linguist-documentation" };
  }
  const own = values["strauss-class"] as DiffClass | undefined;
  return own && STRAUSS_CLASSES.has(own)
    ? { class: own, reason: `attribute strauss-class=${own}` }
    : undefined;
}
