import { describe, expect, test } from "vitest";
import type { KbAnchor, KbRecord } from "../kb-record.schema.js";
import { classifyDiff } from "./classify.js";
import { PATH_RULES, type KbClass, type KbClassifyFile } from "./index.js";

function file(
  filePath: string,
  rest: Partial<KbClassifyFile> = {},
): KbClassifyFile {
  return { filePath, hunks: [], ...rest };
}

function classOf(input: KbClassifyFile, records: KbRecord[] = []): KbClass {
  return (classifyDiff([input], { records })[0] as { class: KbClass }).class;
}

function override(
  conceptId: string,
  tag: string,
  anchors: KbAnchor[],
  frontmatter: Partial<KbRecord["frontmatter"]> = {},
): KbRecord {
  return {
    conceptId,
    frontmatter: {
      type: "fact",
      strauss_status: "accepted",
      tags: ["review", tag],
      generated: { by: "test", at: "2026-08-01T00:00:00Z" },
      strauss_anchors: anchors,
      ...frontmatter,
    } as KbRecord["frontmatter"],
    body: "Body.",
  };
}

/** One path per row of the table, so a row added without a case shows up. */
const PATHS: Record<string, KbClass> = {
  "src/order.spec.ts": "test",
  "src/__tests__/order.ts": "test",
  "src/__mocks__/order.ts": "test",
  "test/helpers.ts": "test",
  "tests/helpers.ts": "test",
  "packages/api/order.test.tsx": "test",
  ".github/workflows/ci.yml": "ci",
  ".circleci/config.yml": "ci",
  "ci/release.yaml": "ci",
  Dockerfile: "ci",
  "deploy/Dockerfile.web": "ci",
  "infra/main.tf": "ci",
  "docs/README.md": "docs",
  "CHANGELOG.md": "docs",
  "docs/guide/index.html": "docs",
  LICENSE: "docs",
  "pnpm-lock.yaml": "lockfile",
  "package-lock.json": "lockfile",
  "yarn.lock": "lockfile",
  "Cargo.lock": "lockfile",
  "go.sum": "lockfile",
  "package.json": "config",
  ".strauss/kb/log.jsonl": "config",
  "app/settings.toml": "config",
  "app/settings.ini": "config",
  "src/app.yaml": "config",
  ".env.local": "config",
  "tsconfig.build.json": "config",
  "vitest.config.ts": "config",
  ".eslintrc.cjs": "config",
  ".prettierrc": "config",
  "src/order.service.ts": "source",
  // Every rule is anchored at both ends, so a path that merely contains one of
  // their words is source.
  "contest/foo.ts": "source",
  "src/config.service.ts": "source",
  "src/docs-parser.ts": "source",
  "packages/ci/index.ts": "source",
  "src/tsconfig-loader.ts": "source",
  "report.env.ts": "source",
  "src/DockerfileParser.ts": "source",
};

describe("classifyDiff path table", () => {
  test("every row of the table is reachable", () => {
    const reached = new Set(
      Object.keys(PATHS).flatMap((path) => {
        const rule = PATH_RULES.find((entry) => entry.test.test(path));
        return rule ? [rule.name] : [];
      }),
    );
    expect([...reached].sort()).toEqual(
      PATH_RULES.map((rule) => rule.name).sort(),
    );
  });

  test.for(Object.entries(PATHS))("%s is %s", ([path, expected]) => {
    expect(classOf(file(path))).toBe(expected);
  });

  test("the reason names the rule that fired", () => {
    expect(classifyDiff([file("src/order.spec.ts")])[0]).toMatchObject({
      class: "test",
      reason: "test-path",
    });
    expect(classifyDiff([file("src/order.service.ts")])[0]).toMatchObject({
      class: "source",
      reason: "default",
    });
  });
});

describe("classifyDiff precedence", () => {
  const generated = file("src/protocol/types.ts", {
    header: [
      "// Code generated by protoc. DO NOT EDIT.",
      "export const x = 1;",
    ],
  });

  test("a generated header beats the path table", () => {
    expect(
      classOf(file("src/settings.json", { header: ["// @generated"] })),
    ).toBe("generated");
  });

  test("a banner past the window is not a banner", () => {
    expect(
      classOf(
        file("src/order.service.ts", {
          header: [...Array<string>(20).fill(""), "// @generated"],
        }),
      ),
    ).toBe("source");
  });

  test("a file-only override beats the header", () => {
    expect(
      classOf(generated, [
        override("fact.moved", "review:move", [{ file: generated.filePath }]),
      ]),
    ).toBe("rename");
  });

  test("the override's reason names the record", () => {
    expect(
      classifyDiff([generated], {
        records: [
          override("fact.moved", "review:move", [{ file: generated.filePath }]),
        ],
      })[0],
    ).toMatchObject({ reason: "kb-override fact.moved" });
  });

  test("review:generated asserts generated over the path table", () => {
    expect(
      classOf(file("src/order.service.ts"), [
        override("fact.emitted", "review:generated", [
          { file: "src/order.service.ts" },
        ]),
      ]),
    ).toBe("generated");
  });

  test("a rejected override does not fire", () => {
    expect(
      classOf(generated, [
        override("fact.moved", "review:move", [{ file: generated.filePath }], {
          strauss_status: "rejected",
        }),
      ]),
    ).toBe("generated");
  });

  test("a superseded override does not fire", () => {
    expect(
      classOf(generated, [
        override("fact.moved", "review:move", [{ file: generated.filePath }], {
          strauss_status: "superseded",
          strauss_superseded_by: "fact.later",
        }),
        override("fact.later", "review:move", []),
      ]),
    ).toBe("generated");
  });

  test("a non-fact record carrying the tag is not an override", () => {
    expect(
      classOf(generated, [
        {
          ...override("decision.moved", "review:move", [
            { file: generated.filePath },
          ]),
          frontmatter: {
            ...override("decision.moved", "review:move", [
              { file: generated.filePath },
            ]).frontmatter,
            type: "decision",
          },
        },
      ]),
    ).toBe("generated");
  });

  test("a symbol anchor nothing resolved still covers its file", () => {
    expect(
      classOf(
        file("src/order.service.ts", { hunks: [{ startLine: 5, endLine: 9 }] }),
        [
          override("fact.barrel", "review:boilerplate", [
            { file: "src/order.service.ts", symbol: "listOrders" },
          ]),
        ],
      ),
    ).toBe("boilerplate");
  });

  test("a resolved symbol anchor classifies only the hunks it covers", () => {
    const [only] = classifyDiff(
      [
        file("src/order.service.ts", {
          hunks: [
            { startLine: 5, endLine: 9 },
            { startLine: 100, endLine: 110 },
          ],
        }),
      ],
      {
        records: [
          override("fact.barrel", "review:boilerplate", [
            { file: "src/order.service.ts", symbol: "listOrders" },
          ]),
        ],
        symbolRanges: [
          {
            file: "src/order.service.ts",
            symbol: "listOrders",
            startLine: 100,
            endLine: 140,
          },
        ],
      },
    );

    expect(only).toMatchObject({ class: "source", reason: "default" });
    expect(only?.hunks).toEqual([
      { startLine: 5, endLine: 9, class: "source", reason: "default" },
      {
        startLine: 100,
        endLine: 110,
        class: "boilerplate",
        reason: "kb-override fact.barrel",
      },
    ]);
  });

  test("hunks are absent when every one agrees with the file", () => {
    expect(
      classifyDiff([
        file("src/order.service.ts", { hunks: [{ startLine: 1, endLine: 2 }] }),
      ])[0],
    ).not.toHaveProperty("hunks");
  });
});

describe("classifyDiff rename", () => {
  test("a rename with no content hunks is one", () => {
    expect(
      classifyDiff([
        file("src/new.service.ts", {
          renamedFrom: "src/old.service.ts",
          similarity: 100,
        }),
      ])[0],
    ).toEqual({
      filePath: "src/new.service.ts",
      class: "rename",
      reason: "rename src/old.service.ts",
      renamedFrom: "src/old.service.ts",
    });
  });

  test("a rename that also changed lines is classified on its content", () => {
    expect(
      classifyDiff([
        file("src/new.service.ts", {
          renamedFrom: "src/old.service.ts",
          similarity: 95,
          hunks: [
            { startLine: 7, endLine: 7, lines: ["const x = compute();"] },
          ],
        }),
      ])[0],
    ).toMatchObject({
      class: "source",
      reason: "default",
      renamedFrom: "src/old.service.ts",
    });
  });

  test("similarity below the threshold is not a rename", () => {
    expect(
      classOf(
        file("src/new.service.ts", {
          renamedFrom: "src/old.service.ts",
          similarity: 89,
        }),
      ),
    ).toBe("source");
  });

  test("the path table wins over rename", () => {
    expect(
      classOf(
        file("docs/new.md", { renamedFrom: "docs/old.md", similarity: 100 }),
      ),
    ).toBe("docs");
  });
});

describe("classifyDiff boilerplate", () => {
  const shapes = [
    'import { Order } from "./order.js";',
    'export * from "./order.js";',
    "export type { Order }",
    "class Empty {}",
    "}",
  ];

  const withLines = (lines: string[]): KbClassifyFile =>
    file("src/barrel.ts", { hunks: [{ startLine: 1, endLine: 1, lines }] });

  test("a file of only boilerplate shapes is boilerplate", () => {
    expect(classOf(withLines(shapes))).toBe("boilerplate");
  });

  test("exactly at the threshold is boilerplate", () => {
    expect(
      classOf(withLines([...shapes.slice(0, 4), "const x = compute();"])),
    ).toBe("boilerplate");
  });

  test("one line under the threshold is source", () => {
    expect(
      classOf(
        withLines([
          ...shapes.slice(0, 3),
          "const x = compute();",
          "const y = compute();",
        ]),
      ),
    ).toBe("source");
  });

  test("blank lines are neither counted nor held against the file", () => {
    expect(classOf(withLines([...shapes, "", "  "]))).toBe("boilerplate");
  });

  test("a class with a body on the next line is not a shell", () => {
    expect(
      classOf(withLines(["export class PayGuard extends AdminGuard {"])),
    ).toBe("source");
  });

  test("a parser that kept no lines cannot fire the rule", () => {
    expect(
      classOf(file("src/barrel.ts", { hunks: [{ startLine: 1, endLine: 5 }] })),
    ).toBe("source");
  });

  test("the threshold is a caller's to move", () => {
    const [only] = classifyDiff(
      [withLines([...shapes.slice(0, 3), "const x = compute();"])],
      { thresholds: { boilerplate: 0.7 } },
    );
    expect(only).toMatchObject({
      class: "boilerplate",
      reason: "boilerplate 75%",
    });
  });
});

describe("classifyDiff generated header from the diff alone", () => {
  test("added lines inside the window count as the head of the file", () => {
    expect(
      classOf(
        file("src/protocol/types.ts", {
          hunks: [
            {
              startLine: 1,
              endLine: 2,
              lines: ["// @generated by protoc", "export const x = 1;"],
            },
          ],
        }),
      ),
    ).toBe("generated");
  });

  test("added lines past the window do not", () => {
    expect(
      classOf(
        file("src/protocol/types.ts", {
          hunks: [
            { startLine: 40, endLine: 40, lines: ["// @generated by protoc"] },
          ],
        }),
      ),
    ).toBe("source");
  });
});
