import { describe, expect, test } from "vitest";
import type { KbAnchor, KbRecord } from "../kb-record.schema.js";
import { classifyDiff } from "./classify.js";
import type { KbClass, KbClassifyFile, KbClassifyOptions } from "./index.js";

function file(
  filePath: string,
  rest: Partial<KbClassifyFile> = {},
): KbClassifyFile {
  return { filePath, hunks: [], ...rest };
}

function classOf(
  input: KbClassifyFile,
  records: KbRecord[] = [],
  options: KbClassifyOptions = {},
): KbClass {
  return (
    classifyDiff([input], { ...options, records })[0] as { class: KbClass }
  ).class;
}

function override(
  conceptId: string,
  tag: string,
  anchors: KbAnchor[],
  frontmatter: Partial<KbRecord["frontmatter"]> = {},
): KbRecord {
  return {
    conceptId,
    frontmatter: {
      type: "fact",
      strauss_status: "accepted",
      tags: ["review", tag],
      generated: { by: "test", at: "2026-08-01T00:00:00Z" },
      strauss_anchors: anchors,
      ...frontmatter,
    } as KbRecord["frontmatter"],
    body: "Body.",
  };
}

describe("classifyDiff KB overrides", () => {
  const generated = file("src/protocol/types.ts", {
    header: [
      "// Code generated by protoc. DO NOT EDIT.",
      "export const x = 1;",
    ],
  });

  test("a file-only override beats the banner", () => {
    expect(
      classOf(generated, [
        override("fact.moved", "review:move", [{ file: generated.filePath }]),
      ]),
    ).toBe("rename");
  });

  test("an override beats a .gitattributes class", () => {
    expect(
      classOf(
        file("pnpm-lock.yaml"),
        [
          override("fact.gen", "review:generated", [
            { file: "pnpm-lock.yaml" },
          ]),
        ],
        {
          attributes: new Map([
            [
              "pnpm-lock.yaml",
              { class: "lockfile", reason: "attribute strauss-class=lockfile" },
            ],
          ]),
        },
      ),
    ).toBe("generated");
  });

  test("the override's reason names the record", () => {
    expect(
      classifyDiff([generated], {
        records: [
          override("fact.moved", "review:move", [{ file: generated.filePath }]),
        ],
      })[0],
    ).toMatchObject({ reason: "kb-override fact.moved" });
  });

  test("review:generated asserts generated over source", () => {
    expect(
      classOf(file("src/order.service.ts"), [
        override("fact.emitted", "review:generated", [
          { file: "src/order.service.ts" },
        ]),
      ]),
    ).toBe("generated");
  });

  test("a rejected override does not fire", () => {
    expect(
      classOf(generated, [
        override("fact.moved", "review:move", [{ file: generated.filePath }], {
          strauss_status: "rejected",
        }),
      ]),
    ).toBe("generated");
  });

  test("a superseded override does not fire", () => {
    expect(
      classOf(generated, [
        override("fact.moved", "review:move", [{ file: generated.filePath }], {
          strauss_status: "superseded",
          strauss_superseded_by: "fact.later",
        }),
        override("fact.later", "review:move", []),
      ]),
    ).toBe("generated");
  });

  test("a non-fact record carrying the tag is not an override", () => {
    const record = override("decision.moved", "review:move", [
      { file: generated.filePath },
    ]);
    expect(
      classOf(generated, [
        { ...record, frontmatter: { ...record.frontmatter, type: "decision" } },
      ]),
    ).toBe("generated");
  });

  test("a symbol anchor nothing resolved still covers its file", () => {
    expect(
      classOf(
        file("src/order.service.ts", { hunks: [{ startLine: 5, endLine: 9 }] }),
        [
          override("fact.barrel", "review:boilerplate", [
            { file: "src/order.service.ts", symbol: "listOrders" },
          ]),
        ],
      ),
    ).toBe("boilerplate");
  });

  test("a resolved symbol anchor classifies only the hunks it covers", () => {
    const [only] = classifyDiff(
      [
        file("src/order.service.ts", {
          hunks: [
            { startLine: 5, endLine: 9 },
            { startLine: 100, endLine: 110 },
          ],
        }),
      ],
      {
        records: [
          override("fact.barrel", "review:boilerplate", [
            { file: "src/order.service.ts", symbol: "listOrders" },
          ]),
        ],
        symbolRanges: [
          {
            file: "src/order.service.ts",
            symbol: "listOrders",
            startLine: 100,
            endLine: 140,
          },
        ],
      },
    );

    expect(only).toMatchObject({ class: "source", reason: "default" });
    expect(only?.hunks).toEqual([
      { startLine: 5, endLine: 9, class: "source", reason: "default" },
      {
        startLine: 100,
        endLine: 110,
        class: "boilerplate",
        reason: "kb-override fact.barrel",
      },
    ]);
  });

  test("with no override, what the repository declares decides", () => {
    expect(classOf(file("docs/README.md"))).toBe("docs");
    expect(classOf(file("docs/README.md"), [], { repoDeclares: true })).toBe(
      "source",
    );
  });
});
