import type { KbClass } from "./model.js";

/**
 * The rules, as data. A rule is added by adding a row, so the table is what a
 * reader checks against a path rather than a chain of branches.
 */
export type KbPathRule = { name: string; class: KbClass; test: RegExp };

/**
 * Path patterns, first match wins. `lockfile` sits above `config` because a
 * lock file is also a `.yaml`, and `ci` above it because a workflow is a
 * `.yml`.
 */
export const PATH_RULES: readonly KbPathRule[] = [
  {
    name: "test-path",
    class: "test",
    test: /(^|\/)(__tests__|__mocks__|tests?)\/|\.(spec|test)\.[^/]+$/,
  },
  {
    name: "ci-path",
    class: "ci",
    test: /(^|\/)\.github\/|(^|\/)(\.circleci|\.buildkite|\.gitlab|ci)\/[^/]*\.ya?ml$|(^|\/)Dockerfile(\.[^/]*)?$|\.tf$/,
  },
  {
    name: "docs-path",
    class: "docs",
    test: /\.md$|(^|\/)docs\/|(^|\/)LICENSE(\.(md|txt|rst))?$/,
  },
  {
    name: "lockfile-path",
    class: "lockfile",
    test: /(^|\/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock|Cargo\.lock|go\.sum)$/,
  },
  {
    name: "config-path",
    class: "config",
    // `.jsonl` rides with `.json`: an append-only log of JSON is configuration
    // data too, and calling it source would send a reviewer to read it. Every
    // arm is anchored at both ends: `src/tsconfig-loader.ts` and `report.env.ts`
    // are source, not config.
    test: /\.(jsonc?|jsonl|ya?ml|toml|ini)$|(^|\/)\.env(?![^/]*\.[cm]?[jt]sx?$)([.-][^/]*)?$|[^/]+\.env$|(^|\/)tsconfig[^/]*\.json$|\.config\.[^/]+$|(^|\/)\.(eslintrc|prettierrc)[^/]*$/,
  },
];

/** How far into a file a generator's banner counts as one. */
export const HEADER_LINES = 20;

/**
 * Banners a generator writes. Matched case-insensitively: the convention is
 * shouted in some ecosystems and not in others.
 */
export const GENERATED_MARKERS: readonly RegExp[] = [
  /@generated\b/i,
  /\bdo not edit\b/i,
  /\bcode generated by\b/i,
  /\bthis file was automatically generated\b/i,
];

/**
 * Line shapes carrying no decision: a moved import, a barrel's re-exports, the
 * punctuation around them, and a class whose body is empty on the same line —
 * an opening brace with code behind it is a class someone has to read.
 */
export const BOILERPLATE_SHAPES: readonly { name: string; test: RegExp }[] = [
  { name: "import", test: /^import\b|^\}\s*from\s+["']/ },
  { name: "re-export", test: /^export\s+(\*|\{|type\s*[{*])/ },
  {
    name: "class-shell",
    test: /^(export\s+)?(default\s+)?(abstract\s+)?class\s+[\w$]+[^{]*\{\s*\}$/,
  },
  { name: "punctuation", test: /^[{}()[\],;]+$/ },
];

export function generatedMarker(lines: readonly string[]): string | undefined {
  for (const line of lines.slice(0, HEADER_LINES)) {
    const hit = GENERATED_MARKERS.find((marker) => marker.test(line));
    if (hit) return hit.source.replaceAll("\\b", "");
  }
  return undefined;
}

export function isBoilerplateLine(line: string): boolean {
  return BOILERPLATE_SHAPES.some((shape) => shape.test.test(line));
}
