import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  rmSync,
  utimesSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  afterAll,
  afterEach,
  beforeEach,
  describe,
  expect,
  test,
  vi,
} from "vitest";
import { KbStore } from "../../kb-store.js";

// Counted rather than stubbed: the point of the cache is that the second pass
// opens nothing, and only the real `open` can say whether it did.
const opened: string[] = [];
// Fires between the stat that names a blob and the read that fills it — the
// one window a rewrite can land in.
const hooks = vi.hoisted(() => ({ onOpen: null as null | (() => void) }));
vi.mock("node:fs/promises", async (importOriginal) => {
  const real = await importOriginal<typeof import("node:fs/promises")>();
  return {
    ...real,
    default: real,
    open: async (path: string, ...rest: unknown[]) => {
      opened.push(String(path));
      const handle = await (
        real.open as (...args: unknown[]) => Promise<unknown>
      )(path, ...rest);
      hooks.onOpen?.();
      return handle;
    },
  };
});

const { readHeader, resetHeaderCache } = await import("./header-cache.js");
const { classifyCommand } = await import("./command.js");

const BANNER = "// @generated by protoc. DO NOT EDIT.\n";

describe("readHeader", () => {
  let repo: string;
  let cache: string;

  beforeEach(() => {
    opened.length = 0;
    hooks.onOpen = null;
    resetHeaderCache();
    repo = mkdtempSync(join(tmpdir(), "strauss-kb-header-repo-"));
    cache = mkdtempSync(join(tmpdir(), "strauss-kb-header-cache-"));
    process.env["STRAUSS_KB_CACHE_DIR"] = cache;
    mkdirSync(join(repo, "src"), { recursive: true });
    for (let at = 0; at < 8; at += 1) {
      writeFileSync(
        join(repo, "src", `file-${at}.ts`),
        `${BANNER}export const value${at} = ${at};\n`,
        "utf8",
      );
    }
  });

  afterEach(() => {
    vi.restoreAllMocks();
    rmSync(repo, { recursive: true, force: true });
    rmSync(cache, { recursive: true, force: true });
  });

  afterAll(() => {
    process.env["STRAUSS_KB_CACHE_DIR"] = "off";
  });

  const paths = () => Array.from({ length: 8 }, (_, at) => `src/file-${at}.ts`);

  const pass = async () => {
    for (const file of paths()) await readHeader(repo, file);
  };

  test("a second run over the same tree opens nothing", async () => {
    await pass();
    expect(opened).toHaveLength(8);

    await pass();
    expect(opened).toHaveLength(8);
  });

  test("a cold process still opens nothing when the disk half holds it", async () => {
    await pass();
    opened.length = 0;
    // What a second `strauss-kb classify` sees: an empty memo, a warm cache.
    resetHeaderCache();

    await pass();
    expect(opened).toHaveLength(0);
    expect(await readHeader(repo, "src/file-0.ts")).toEqual([
      BANNER.trimEnd(),
      "export const value0 = 0;",
      "",
    ]);
  });

  test("a rewritten file is read again", async () => {
    await pass();
    writeFileSync(
      join(repo, "src/file-0.ts"),
      `${BANNER}export const value0 = 0;\nexport const extra = 1;\n`,
      "utf8",
    );

    const header = await readHeader(repo, "src/file-0.ts");
    expect(opened).toHaveLength(9);
    expect(header).toContain("export const extra = 1;");
  });

  test("STRAUSS_KB_CACHE_DIR=off keeps the disk half out of it", async () => {
    process.env["STRAUSS_KB_CACHE_DIR"] = "off";
    await pass();
    resetHeaderCache();

    await pass();
    expect(opened).toHaveLength(16);
  });

  test("the read is bounded however large the file is", async () => {
    writeFileSync(
      join(repo, "src/big.ts"),
      `${BANNER}${"// filler\n".repeat(200_000)}`,
      "utf8",
    );

    const header = await readHeader(repo, "src/big.ts");
    expect(header).toHaveLength(20);
  });

  test("a path that escapes the root is never opened", async () => {
    expect(await readHeader(repo, "../outside.ts")).toBeUndefined();
    expect(opened).toHaveLength(0);
  });

  test("a blob rewritten under the read is not written to disk", async () => {
    await readHeader(repo, "src/file-1.ts");
    expect(entries()).toHaveLength(1);

    const raced = `${BANNER}export const value0 = 0;\nexport const raced = 1;\n`;
    hooks.onOpen = () => {
      hooks.onOpen = null;
      writeFileSync(join(repo, "src/file-0.ts"), raced, "utf8");
    };

    expect(await readHeader(repo, "src/file-0.ts")).toContain(
      "export const raced = 1;",
    );
    expect(entries()).toHaveLength(1);
  });

  test("a relative STRAUSS_KB_CACHE_DIR is refused once, and the disk half is off", async () => {
    process.env["STRAUSS_KB_CACHE_DIR"] = "relative-cache";
    const warn = vi.spyOn(process.stderr, "write").mockReturnValue(true);

    await pass();
    resetHeaderCache();
    await pass();

    expect(warn).toHaveBeenCalledTimes(2);
    expect(warn.mock.calls[0]?.[0]).toContain("must be an absolute path");
    expect(opened).toHaveLength(16);
    expect(existsSync(join(process.cwd(), "relative-cache"))).toBe(false);
  });

  test("a cache over its byte cap loses its oldest entries, once per process", async () => {
    const shard = join(cache, "classify", "ff");
    mkdirSync(shard, { recursive: true });
    const junk = "x".repeat(512 * 1_024);
    const names = Array.from(
      { length: 20 },
      (_, at) => `${String(at).padStart(2, "0")}${"f".repeat(62)}.json`,
    );
    names.forEach((name, at) => {
      writeFileSync(join(shard, name), junk, "utf8");
      utimesSync(join(shard, name), 1_000_000 + at * 60, 1_000_000 + at * 60);
    });

    await readHeader(repo, "src/file-0.ts");
    const left = readdirSync(shard);
    expect(left.length).toBeLessThan(20);
    expect(left).not.toContain(names[0]);
    expect(left).toContain(names[19]);

    // One sweep per process: the next write does not walk the directory again.
    writeFileSync(join(shard, `aa${"f".repeat(62)}.json`), junk, "utf8");
    await readHeader(repo, "src/file-1.ts");
    expect(readdirSync(shard)).toHaveLength(left.length + 1);
  });

  test("a warm cache classifies exactly as a cold one", async () => {
    const bundle = mkdtempSync(join(tmpdir(), "strauss-kb-header-bundle-"));
    const ctx = { store: new KbStore(), actor: "agent:test", now: () => "" };
    const input = classifyCommand.input.parse({
      bundlePath: bundle,
      repoRoot: repo,
      offline: true,
      files: paths().map((filePath) => ({
        filePath,
        hunks: [{ startLine: 1, endLine: 2 }],
      })),
    });

    const cold = await classifyCommand.run(ctx, input);
    resetHeaderCache();
    const warm = await classifyCommand.run(ctx, input);

    expect(warm).toEqual(cold);
    rmSync(bundle, { recursive: true, force: true });
  });

  /** Every entry the disk half holds, however it is sharded. */
  function entries(): string[] {
    const dir = join(cache, "classify");
    if (!existsSync(dir)) return [];
    return readdirSync(dir, { recursive: true })
      .map(String)
      .filter((name) => name.endsWith(".json"));
  }
});
